//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ComputerShop.Stock.ApiClient
{
    public interface IApiClient
    {
        Task<StockItem> ApiStockDeleteAsync(int productId);
        Task<StockItem> ApiStockDeleteAsync(int productId, CancellationToken cancellationToken);
        Task<ICollection<StockItem>> ApiStockGetAsync();
        Task<ICollection<StockItem>> ApiStockGetAsync(CancellationToken cancellationToken);
        Task<StockItem> ApiStockGetAsync(int productId);
        Task<StockItem> ApiStockGetAsync(int productId, CancellationToken cancellationToken);
        Task<StockItem> ApiStockPostAsync(StockItem body);
        Task<StockItem> ApiStockPostAsync(StockItem body, CancellationToken cancellationToken);
        Task ApiStockPutAsync(int id, StockItem body);
        Task ApiStockPutAsync(int id, StockItem body, CancellationToken cancellationToken);
    }
}