// <auto-generated />
using ComputerShop.Stock.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComputerShop.Stock.Api.Migrations
{
    [DbContext(typeof(ComputerShopStockApiContext))]
    [Migration("20210207155654_InsertInitialData")]
    partial class InsertInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComputerShop.Stock.Api.Models.StockItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountInStock")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StockItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountInStock = 5,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            AmountInStock = 9,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            AmountInStock = 7,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            AmountInStock = 14,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            AmountInStock = 8,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            AmountInStock = 0,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            AmountInStock = 6,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            AmountInStock = 12,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            AmountInStock = 3,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            AmountInStock = 4,
                            ProductId = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
